version: '3.8'

services:
  app:
    build: .
    image: photo-app
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./uploads:/app/storage/uploads
    environment:
      DATABASE_URL: "file:./data/prod.db"
